### ISSUE TITLE
Apparent errors in validation when user types in something during `sleep`

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/dinner-party#39]
As my mentor had warned me before implementing `sleep`, this causes some strange behaviours with input validation.

In the screenshot below, it seems like the program rejects the input `y`, which should be accepted.

On closer inspection, however, we can see that the user already entered `y` once, before the next question appeared.

![apparent-validation-error-sleep-timeout](https://github.com/blahosyl/dinner-party/assets/26421503/0fb38b32-1292-465d-a2da-ce3ab1ed735a)

Since timeouts with `sleep` enhance the user experience, especially when giving a confirmation message before clearing the screen, I decided not to remove these. Instead, I intend to modify the validation error messages such that they also show the user input that is being rejected.

Code to be modified
- [x] initial question
- [x] add more dishes question
- [x] dish selection: out of range
- [x] #41

**Comment by blahosyl** [comment]
Seem to have introduced a bug:

```

Type in the number of the dish you'd like to add: 45
Traceback (most recent call last):
  File "/app/run.py", line 195, in <module>
    _shopping_list.unify_ingredients(_dishes.select_dish(), _data)
  File "/app/planner.py", line 66, in select_dish
    while dish_number < 1 or dish_number > len(self.dish_data) - 1:
TypeError: '<' not supported between instances of 'str' and 'int'
```

**Comment by blahosyl** [comment]
Breaking bug fixed. However, the user input is still not always shown correctly in the `except` block:

<img width="616" alt="bug-input-except-block" src="https://github.com/blahosyl/dinner-party/assets/26421503/87a1036c-c5c4-429b-8f4f-7eebbbea28bd">
